name: BetterFactions
description: A small plugin
author: Camoleopard and Moulberry
commands:
  sphere:
    description: gives equipment
  cenchant:
    description: Gives an enchanted item
  tnt:
    description: Summons special tnt!
  kit:
    description: Gives you kit items!
version: 1.0
main: me.camoleopard.betterfactions.BetterFactions
depend: [Factions]